"use client";
import { useState } from "react";
import type { SiteContentData } from "@/lib/content";
import { Nav } from "./Nav";
import { LeadForm } from "./LeadForm";

type Testimonial={id:string;quote:string;name:string;context:string|null};
const specialties=[
 ["◌","Acreage & larger homesites","Room to breathe, grow, gather, and make the outdoors part of everyday life."],
 ["⌂","Farmhouse-style homes","Character-rich homes that balance warm design with practical living."],
 ["♧","Privacy & outdoor living","Space for gardens, animals, play, entertaining, and a quieter pace."],
 ["◇","Neighborhood homes","The right fit in an established community close to the life you already love."],
 ["＋","New construction","Builder options, incentives, timelines, and contract details made easier to navigate."],
 ["→","Relocation & lifestyle moves","Local insight to help you choose an area—not just an address—with confidence."]
];

export function HomePage({content:c,testimonials}:{content:SiteContentData;testimonials:Testimonial[]}){
 const [form,setForm]=useState<{open:boolean;type?:"BUYER"|"SELLER"}>({open:false}); const show=(type?:"BUYER"|"SELLER")=>setForm({open:true,type});
 const phoneHref=c.phone.startsWith("[")?"#":`tel:${c.phone.replace(/[^+\d]/g,"")}`; const textHref=c.phone.startsWith("[")?"#":`sms:${c.phone.replace(/[^+\d]/g,"")}`;
 return <><Nav instagram={c.instagramUrl} cta={c.primaryCta} onLead={show}/><main id="main">
  <section className="hero" id="home"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow" style={{color:"#dac18f"}}>Florida real estate, personally guided</span><h1>{c.heroHeading}</h1><p className="lead">{c.heroMessage}</p><div className="actions"><button className="button" onClick={()=>show()}>{c.primaryCta}</button><a className="button secondary" href="#about">Meet Me</a></div><p className="micro">Personal guidance. Local insight. A real person by your side.</p></div><div className="portrait">{c.profileImageUrl?<img src={c.profileImageUrl} alt="Amanda Alves, Florida Realtor"/>:<div className="portrait-placeholder"><p><strong>My professional portrait</strong><br/><small>I’ll share my photo here soon.</small></p></div>}</div></div></section>
  <div className="container pathways" aria-label="Buyer and seller options"><article className="path-card" id="buy"><div className="path-icon">⌂</div><h3>{c.buyerHeading}</h3><p>{c.buyerMessage}</p><button className="button outline" onClick={()=>show("BUYER")}>Find My Next Home</button></article><article className="path-card" id="sell"><div className="path-icon">◇</div><h3>{c.sellerHeading}</h3><p>{c.sellerMessage}</p><button className="button" onClick={()=>show("SELLER")}>Explore My Selling Options</button></article></div>
  <section className="section specialty"><div className="container"><div className="section-head"><span className="eyebrow">Space for what matters</span><h2>{c.specialtyHeading}</h2><p>{c.specialtyMessage}</p></div><div className="specialty-grid">{specialties.map(([icon,title,text])=><article className="special-card" key={title}><span aria-hidden>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section className="section" id="about"><div className="container about-grid"><div className="family-frame">{c.familyImageUrl?<img src={c.familyImageUrl} alt="Amanda Alves with her husband and three sons"/>:<div className="family-placeholder"><p><strong>My family photograph</strong><br/><small>I’ll share my family photo here soon.</small></p></div>}</div><div className="bio"><span className="eyebrow">Meet Me</span><h2>Home is where life takes root.</h2><p>{c.aboutBio}</p><button className="button dark" onClick={()=>show()}>Let’s Talk About Your Next Move</button></div></div></section>
  <section className="section steps"><div className="container"><div className="section-head center"><span className="eyebrow" style={{color:"#dac18f"}}>A clear path forward</span><h2>How I help</h2></div><div className="step-grid">{[["01","Share Your Vision","Tell me what you are looking for, what is changing, and what matters most."],["02","Build Your Strategy","I’ll provide personalized guidance and a clear plan based on your goals and timeline."],["03","Move Forward Confidently","I’ll support you attentively through your purchase or sale, from our first conversation through closing."]].map(x=><article key={x[0]}><div className="step-no">{x[0]}</div><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
  {testimonials.length>0&&<section className="section"><div className="container"><div className="section-head center"><span className="eyebrow">Client stories</span><h2>Guidance that feels personal</h2></div><div className="testimonials">{testimonials.map(t=><blockquote className="quote" key={t.id}><p>“{t.quote}”</p><footer><strong>{t.name}</strong>{t.context&&<><br/><small>{t.context}</small></>}</footer></blockquote>)}</div></div></section>}
  <section className="section contact" id="contact"><div className="container"><div className="contact-card"><div><span className="eyebrow">Start a conversation</span><h2>Your next move can begin with one simple hello.</h2><div className="contact-list"><strong>Amanda Alves, Realtor®</strong><span>{c.brokerageName}</span><span>Florida license: {c.licenseNumber}</span><span>I serve {c.serviceAreas}</span><a href={phoneHref}>{c.phone}</a><a href={`mailto:${c.email}`}>{c.email}</a></div></div><div className="contact-actions"><a className="button outline" href={phoneHref}>Call Me</a><a className="button outline" href={textHref}>Text Me</a><a className="button outline" href={`mailto:${c.email}`}>Email Me</a><a className="button outline" href={c.instagramUrl} target="_blank" rel="noreferrer">Visit My Instagram</a><button className="button dark" style={{gridColumn:"1/-1"}} onClick={()=>show()}>{c.primaryCta}</button></div></div></div></section>
 </main><footer className="footer"><div className="container"><div className="footer-grid"><div><h3>Amanda Alves, Realtor®</h3><p>{c.brokerageName}<br/>{c.brokerageContact}<br/>Florida license: {c.licenseNumber}</p><span className="eho"><span className="eho-mark" aria-hidden>⌂</span> Equal Housing Opportunity</span></div><div className="footer-links"><strong>Explore</strong><a href="#about">About</a><a href="#buy">Buy</a><a href="#sell">Sell</a><a href="#contact">Contact</a></div><div className="footer-links"><strong>Information</strong><a href="/privacy">Privacy Policy</a><a href="/terms">Terms of Use</a><a href="/accessibility">Accessibility</a><a href={c.instagramUrl}>Instagram</a></div></div><div className="legal-note">{c.disclosureText}<br/>© {new Date().getFullYear()} Amanda Alves. All rights reserved.</div></div></footer><LeadForm open={form.open} type={form.type} onClose={()=>setForm({open:false})}/></>;
}
