"use client";
import { useEffect, useId, useState } from "react";

import { states } from "@/lib/form-fields";
import { compressPhoto } from "@/lib/compress-photo";

type LeadType="BUYER"|"SELLER"; type Data=Record<string,string|boolean>;
const initial:Data={firstName:"",lastName:"",email:"",phone:"",preferredContact:"Text",bestTime:"",language:"English",source:"",state:"Florida",generalDetails:"",consentPrivacy:false,consentCallsTexts:false};
const options=(values:string[])=>values.map(v=><option key={v}>{v}</option>);
function Field({label,name,data,setData,type="text",required=false,full=false,children}:{label:string;name:string;data:Data;setData:(d:Data)=>void;type?:string;required?:boolean;full?:boolean;children?:React.ReactNode}){const id=useId();return <div className={`field ${full?"full":""}`}><label htmlFor={id}>{label}{required?" *":""}</label>{children?<select id={id} name={name} value={String(data[name]??"")} required={required} onChange={e=>setData({...data,[name]:e.target.value})}>{children}</select>:type==="textarea"?<textarea id={id} name={name} value={String(data[name]??"")} required={required} onChange={e=>setData({...data,[name]:e.target.value})}/>:<input id={id} name={name} type={type} value={String(data[name]??"")} required={required} onChange={e=>setData({...data,[name]:e.target.value})}/>}</div>}

export function LeadForm({open,type:seed,onClose}:{open:boolean;type?:LeadType;onClose:()=>void}){
 const [step,setStep]=useState(seed?2:1),[leadType,setLeadType]=useState<LeadType|undefined>(seed),[data,setData]=useState<Data>(initial),[files,setFiles]=useState<File[]>([]),[processing,setProcessing]=useState(false),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState(""),[successNote,setSuccessNote]=useState("");
 useEffect(()=>{if(open){document.body.classList.add("modal-open");setDone(false);setError("");setSuccessNote("");const saved=localStorage.getItem("amanda-lead-draft");if(saved)try{const parsed=JSON.parse(saved);setData({...initial,...parsed.data})}catch{}if(seed){setLeadType(seed);setStep(2)}else{setLeadType(undefined);setStep(1)}}else document.body.classList.remove("modal-open");return()=>document.body.classList.remove("modal-open")},[open,seed]);
 useEffect(()=>{if(open&&!done)localStorage.setItem("amanda-lead-draft",JSON.stringify({data,leadType,step}))},[data,leadType,step,open,done]);
 if(!open)return null;
 const select=(t:LeadType)=>{setLeadType(t);setStep(2)};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");setSuccessNote("");try{const key=crypto.randomUUID();const fd=new FormData();const query=new URLSearchParams(window.location.search);const attribution={campaign:query.get("utm_campaign")||"",medium:query.get("utm_medium")||"",referrer:query.get("utm_source")||"",placement:query.get("source")||"",landingPath:window.location.pathname};fd.append("data",JSON.stringify({...data,attribution,type:leadType,idempotencyKey:key}));if(leadType==="SELLER")files.forEach(f=>fd.append("files",f));const r=await fetch("/api/leads",{method:"POST",body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to send your request.");if(j.autoResponseSent===false)setSuccessNote("I received your inquiry, but the confirmation email could not be delivered.");localStorage.removeItem("amanda-lead-draft");setDone(true)}catch(e){setError(e instanceof Error?e.message:"Unable to submit.")}finally{setBusy(false)}};
 return <div className="modal" role="dialog" aria-modal="true" aria-labelledby="lead-title" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal-panel"><div className="modal-head"><div><span className="eyebrow">A thoughtful first step</span><h2 id="lead-title">{done?"Thank you":step===1?"How can I help you?":leadType==="BUYER"?"Tell me about your next home":"Tell me about your property"}</h2></div><button className="close" onClick={onClose} aria-label="Close form">×</button></div><div className="progress"><div style={{width:done?"100%":step===1?"33%":"72%"}}/></div>
 {done?<div className="success"><div style={{fontSize:"3rem"}}>✓</div><h2>Your request is on its way.</h2><p>Thank you—I’ll personally review the details you shared and contact you within 24 hours. You’ve taken the first step, and you’re in caring, capable hands.</p>{successNote&&<p className="notice">{successNote}</p>}<button className="button dark" onClick={onClose}>Return to website</button></div>:step===1?<div className="form-body"><p>Choose the path that feels most like your next move. You can share only what you know right now.</p><div className="choice-grid"><button className="choice" onClick={()=>select("BUYER")}><strong>⌂ I want to buy a home</strong><br/><small>Tell me what home and lifestyle you’re looking for.</small></button><button className="choice" onClick={()=>select("SELLER")}><strong>◇ I want to sell a home</strong><br/><small>Share your property and timing so we can plan well.</small></button></div></div>:<form className="form-body" onSubmit={submit}><div className="fields">
   <Field label="First name" name="firstName" data={data} setData={setData} required/><Field label="Last name" name="lastName" data={data} setData={setData} required/>
   <Field label="Email address" name="email" type="email" data={data} setData={setData} required/><Field label="Phone number" name="phone" type="tel" data={data} setData={setData} required/>
   <Field label="Preferred contact method" name="preferredContact" data={data} setData={setData} required>{options(["Call","Text","Email"])}</Field><Field label="Best time to contact" name="bestTime" data={data} setData={setData}>{options(["","Morning","Afternoon","Evening","Any time"])}</Field>
   <Field label="Preferred language" name="language" data={data} setData={setData}>{options(["English","Portuguese","Spanish","Other"])}</Field><Field label="How did you hear about me?" name="source" data={data} setData={setData}>{options(["","Instagram","Facebook","Referral","Google search","Open house","Other"])}</Field>
   {leadType==="BUYER"?<>
    <Field label="Areas or cities of interest" name="areas" data={data} setData={setData} full required/><Field label="State" name="state" data={data} setData={setData} required>{options(states)}</Field><Field label="Budget range" name="budget" data={data} setData={setData}/><Field label="Property type" name="propertyType" data={data} setData={setData}>{options(["Single-family home","Townhome","Condo","New construction","Acreage / farmhouse","Open to options"])}</Field>
    <Field label="Bedrooms" name="bedrooms" data={data} setData={setData}>{options(["","1","2","3","4","5","6+"])}</Field><Field label="Bathrooms" name="bathrooms" data={data} setData={setData}>{options(["","1","1.5","2","2.5","3","3.5","4","4.5","5+"])}</Field><Field label="Desired lot size" name="lotSize" data={data} setData={setData}/><Field label="Interested in acreage?" name="acreage" data={data} setData={setData}>{options(["Open to it","Yes","No"])}</Field>
    <Field label="Must-have features" name="mustHaves" type="textarea" data={data} setData={setData} full/><Field label="Move-in timeline" name="timeline" data={data} setData={setData}>{options(["","As soon as possible","Within 30 days","1–3 months","3–6 months","6–12 months","More than a year","Just exploring"])}</Field><Field label="Preferred move-in date" name="targetDate" type="date" data={data} setData={setData}/><Field label="Current status" name="currentStatus" data={data} setData={setData}>{options(["Just exploring","Ready to begin","Already pre-approved","Need a lender introduction","Currently working with an agent"])}</Field>
    <Field label="A home to sell first?" name="homeToSell" data={data} setData={setData}>{options(["No","Yes","Unsure"])}</Field><Field label="Financing type, if known" name="financingType" data={data} setData={setData}>{options(["","Cash","Conventional","FHA","VA","USDA","Not sure yet"])}</Field>
   </>:<>
    <Field label="Property address" name="propertyAddress" data={data} setData={setData} full required/><Field label="City" name="city" data={data} setData={setData} required/><Field label="State" name="state" data={data} setData={setData} required>{options(states)}</Field><Field label="ZIP code" name="zip" data={data} setData={setData} required/><Field label="Property type" name="propertyType" data={data} setData={setData}>{options(["","Single-family home","Townhome","Condo","Manufactured home","Land / acreage","Other"])}</Field>
    <Field label="Bedrooms" name="bedrooms" data={data} setData={setData}>{options(["","1","2","3","4","5","6+"])}</Field><Field label="Bathrooms" name="bathrooms" data={data} setData={setData}>{options(["","1","1.5","2","2.5","3","3.5","4","4.5","5+"])}</Field><Field label="Approx. square footage" name="squareFeet" data={data} setData={setData}/><Field label="Approx. lot size" name="lotSize" data={data} setData={setData}/>
    <Field label="Property condition" name="condition" data={data} setData={setData}>{options(["Unsure","Move-in ready","Minor updates needed","Major updates needed"])}</Field><Field label="Desired selling timeline" name="timeline" data={data} setData={setData}>{options(["","As soon as possible","Within 30 days","1–3 months","3–6 months","6–12 months","More than a year","Just exploring"])}</Field><Field label={leadType==="SELLER"?"Preferred selling date":"Preferred move-in date"} name="targetDate" type="date" data={data} setData={setData}/><Field label="Currently occupied?" name="occupied" data={data} setData={setData}>{options(["Yes","No","Sometimes"])}</Field><Field label="Listed with another agent?" name="listed" data={data} setData={setData}>{options(["No","Yes"])}</Field>
    <Field label="Primary reason for considering a sale" name="saleReason" data={data} setData={setData} full/><Field label="Estimated property value (optional)" name="estimatedValue" data={data} setData={setData}/><Field label="Need help buying next?" name="needsBuyerHelp" data={data} setData={setData}>{options(["No","Yes","Unsure"])}</Field><div className="field full"><label htmlFor="seller-photos">Property photos (optional, up to 5)</label><input id="seller-photos" type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={processing||busy} onChange={async e=>{const selected=Array.from(e.target.files||[]);setFiles([]);setError("");if(selected.length>5){setError("Please select no more than five photos.");e.target.value="";return;}setProcessing(true);try{setFiles(await Promise.all(selected.map(compressPhoto)))}catch(err){setError(err instanceof Error?err.message:"Unable to process photos.");e.target.value=""}finally{setProcessing(false)}}}/><small>JPG, PNG, or WebP; up to 20 MB each before automatic compression. Photos are emailed securely with your inquiry.</small>{processing&&<small role="status">Compressing photos…</small>}{files.length>0&&<small>{files.map(f=>`${f.name} (${Math.round(f.size/1024)} KB)`).join(", ")}</small>}</div>
   </>}
   <Field label="Additional questions or details" name="generalDetails" type="textarea" data={data} setData={setData} full/>
   <div className="honeypot"><label>Leave blank<input value={String(data.website||"")} onChange={e=>setData({...data,website:e.target.value})}/></label></div>
 </div><div className="checks"><label className="check"><input type="checkbox" checked={Boolean(data.consentPrivacy)} onChange={e=>setData({...data,consentPrivacy:e.target.checked})} required/><span>I acknowledge the <a href="/privacy" target="_blank"><u>Privacy Policy</u></a> and understand that submitting this form does not create an agency relationship. *</span></label><label className="check"><input type="checkbox" checked={Boolean(data.consentCallsTexts)} onChange={e=>setData({...data,consentCallsTexts:e.target.checked})}/><span>Optional: I consent to calls and text messages about my inquiry. Message and data rates may apply. Consent is not a condition of service.</span></label></div>{error&&<p className="error" role="alert">{error}</p>}<div className="form-nav"><button type="button" className="button outline" onClick={()=>setStep(1)}>Back</button><button className="button dark" disabled={busy||processing}>{busy?"Sending…":"Send My Request"}</button></div></form>}</div></div>
}
